export interface TypeColumunsDataInsert  {
        columnNome: string,
        columnVinculo: string,
        columnMes_Periodo: string,
        columnAno: string,
        columnOrgao: string,
        columnCpf: string,
        columnMatricula: string,
        columnCargo: string,
        columnDataAdmissao: string,
        columnCargaHoraria: string,
        columnValorBruto: string,
        columnValorLiquido: string,
        columnValorDesconto: string,
}